import type { Metadata } from "next";
import { Geist, Geist_Mono , Cormorant_Garamond, Jost, DM_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-cormorant', // Optional: for Tailwind use
  display: 'swap',
});

// export const jost = Jost({
//   subsets: ['latin'],
//   variable: '--font-jost',
//   display: 'swap',
// });

// export const dmMono = DM_Mono({
//   weight: ['400', '500'],
//   subsets: ['latin'],
//   variable: '--font-dm-mono',
//   display: 'swap',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en" data-scroll-behavior="smooth"
      className={`${cormorant.variable} ${geistSans.variable} ${geistMono.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
